### ISSUE TITLE
Issues with Cubase 12.0.60 and 12.0.70

### ISSUE THREAD

**Issue by MrKeyes1979** [bjoluc/cubase-mcu-midiremote#10]
First off. Thank you for your work on this script. (I love it). With that I have a scribble script issue that is only present in Cubase 12.0.60 and the new 12.0.70. (Cubase 12.0.52 Worked great)

Scribble strips will have the wrong track names. ex: I have a track named "Bass" and the scribble strip shows "toms". It isn't with just one track, but many. When I revert to Cubase 12.0.52 the problem is solved. 

Any input you can provide to help solve this problem is greatly appreciated. 

Thanks again for your hard work.

**Comment by bjoluc** [comment]
Hey @MrKeyes1979,

thanks for opening the issue. It has already been brought up in #5 (although in French :sweat_smile:) and #6, and I found a workaround which I released in 1.6.0 today :tada:

Cheers!

**Comment by MrKeyes1979** [comment]
Thank you. For some reason (and I've tried everything that I know) the new script loads but has no functionality. When I manually load the script it works but only for the project currently open. Then when I switch project the xtouch doesn't function. After hours goofing with it I'm reverting back to Cubase 12.0.52. I'm assuming this is probably a cubase issue itself.

**Comment by bjoluc** [comment]
> I'm assuming this is probably a cubase issue itself.

Yes, sadly. I've heard this a few times already. I'm hoping for a more solid MR API in Cubase 13 (12.0.70 will likely be the last update for CB 12, so I'll be investing money again :smiling_face_with_tear: ), but in order to make this happen, we might need to voice these issues at the Steinberg forum – feel free to open a topic there if you have a moment...
