### ISSUE TITLE
Double tap STOP button to RTZ?

### ISSUE THREAD

**Issue by jpert** [bjoluc/cubase-mcu-midiremote#37]
Hi! Brilliant stuff. I am using an X-Touch One with MusicTechTuiton's modifications to your script. I was wondering if it's possible to implement double pressing the Stop button to Return to Zero on the timeline in a future version? Or perhaps if Rewind and Stop were pressed simultaneously it would RTZ it would be easier to implement? Just kicking out ideas

**Comment by bjoluc** [comment]
Hi @jpert,
thanks for the input. In general, I think Shift+Rewind would be intuitive. Only that the X-Touch One doesn't have a shift button :sweat_smile: What do you think about using F6 as a shift button on the X-Touch One? That would give you access to other shift mappings as well :tada:

**Comment by bjoluc** [comment]
Hey @jpert, I have just released a dedicated X-Touch One script in [Version 1.10.0](https://github.com/bjoluc/cubase-mcu-midiremote/releases), so the X-Touch One is officially supported now :tada:
Re your feature request: I've settled on Shift + Rewind for navigating to the project start (sorry that it's not Stop). I did so because I also wanted to add a button for going to the project end which became Shift + Forward then...

**Comment by jpert** [comment]
Working great! Such a shame that no one has solved how to change the scribble strip colors on the X-Touch one in MCU mode the way they have on the regular X-touch and extender. Why have different implementations for practically identical products Behringer?!  If you could figure out how to implement that feature for X-Touch One it would be amazing. Not crazy important but I hate that there is eye candy the hardware can do but I can't access!
